### PR TITLE
use JBrowse BlobFilehandleWrapper (fixes controlled access BAM)

### LINKED ISSUE #101: Controlled access BAM not working; BlobFilehandleWrapper copy not needed & contains buggy typo
BlobFilehandleWrapper module code was copied from JBrowse in #98 along with others to modify file retrieval code to support GDC authentication token.

As I pointed out in the PR, BlobFilehandleWrapper seemed unnecessary to copy since it appeared to be unchanged from the original.

It turns out the return statement here was changed (probably for some local testing?) and breaks BAM retrieval in the `@gmod/bam` code:
https://github.com/LincolnSteinLab/gdc-viewer/blob/develop/gdc-viewer/js/Model/BlobFilehandleWrapper.js#L14
https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Model/BlobFilehandleWrapper.js#L14
https://github.com/GMOD/bam-js/blob/master/src/bamFile.ts#L114

Best fix is to delete BlobFilehandleWrapper copy and use the JBrowse version.

### PR DESCRIPTION
**Pull request by GFJHogue**
Main issue: #101

### CODE REVIEW

File: cypress/integration/ExploreGDC.js [hunk 1]
```diff
@@ -121,9 +121,9 @@ describe('Explore GDC', function() {
         })
 
         checkAllResultsTab(
-            ['Showing 1 to 20 of 3,111', 'TCGA-A5-A1OF', 'TCGA-AJ-A3EK'],
-            ['Showing 1 to 20 of 21,169', 'TP53', 'TTN'],
-            ['Showing 1 to 20 of 120,896', 'chr2:g.208248388C>T', 'chr17:g.7673803G>A']
+            ['Showing 1 to 20 of 3,127', 'TCGA-A5-A1OF', 'TCGA-AJ-A3EK'],
+            ['Showing 1 to 20 of 21,316', 'TTN', 'TP53'],
+            ['Showing 1 to 20 of 132,784', 'chr7:g.140753336A>T', 'chr2:g.208248388C>T']
```
Comment (GFJHogue) [inline cypress/integration/ExploreGDC.js:126]: Opened #103 to avoid stuff like this in the future

File: cypress/integration/ExploreGDC.js [hunk 2]
```diff
@@ -132,9 +132,9 @@ describe('Explore GDC', function() {
         })
 
         checkAllResultsTab(
-            ['Showing 1 to 20 of 365', 'TCGA-A5-A1OF', 'TCGA-AJ-A3EK'],
-            ['Showing 1 to 20 of 575', 'TP53', 'PIK3CA'],
-            ['Showing 1 to 20 of 5,952', 'chr7:g.140753336A>T', 'chr2:g.208248388C>T']
+            ['Showing 1 to 20 of 457', 'TCGA-A5-A1OF', 'TCGA-AJ-A3EK'],
+            ['Showing 1 to 20 of 575', 'TP53', 'BRAF'],
+            ['Showing 1 to 20 of 6,580', 'chr7:g.140753336A>T', 'chr2:g.208248388C>T']
```
Comment (GFJHogue) [inline cypress/integration/ExploreGDC.js:137]: same as above comment
